import type { Executor } from './safety'
import type { EntityAction, FixPatch, FixPatchFile } from './types'

/**
 * Provider-neutral Git boundary used to turn an approved fix into a pull
 * request. The production implementation talks to the GitHub REST API via
 * `fetch` (see {@link createGitHubClient}); tests inject a fake. The Entity
 * only ever opens a PR — it never merges or deploys.
 */
export interface GitClient {
  /** Resolves the base branch and its current head SHA. */
  getBaseRef(): Promise<{ branch: string; sha: string }>
  /** Creates a new branch pointing at `fromSha`. */
  createBranch(name: string, fromSha: string): Promise<void>
  /** Creates or updates a file on `branch` with the full new contents. */
  putFile(branch: string, path: string, contents: string, message: string): Promise<void>
  /** Opens a pull request from `branch` into the base branch. */
  openPullRequest(branch: string, title: string, body: string): Promise<{ number: number; url: string }>
  /** Closes a pull request without merging it. */
  closePullRequest(prNumber: number): Promise<void>
  /** Deletes a branch (used to roll back / clean up). */
  deleteBranch(name: string): Promise<void>
  /** Aggregated CI state for a pull request's head commit. */
  getPrChecks(prNumber: number): Promise<{ state: 'pending' | 'success' | 'failure' }>
}

/** Shape stored in `action.rollbackState` after a successful apply. */
export interface GitRollbackState {
  prNumber: number
  branch: string
}

/**
 * Validates and extracts a {@link FixPatch} from an action's payload. Returns
 * `undefined` when the patch is absent or malformed, so the caller can keep the
 * action review-only and refuse to apply it.
 */
export function readActionPatch(action: Pick<EntityAction, 'payload'>): FixPatch | undefined {
  const raw = action.payload?.patch
  if (!raw || typeof raw !== 'object') return undefined
  const obj = raw as Record<string, unknown>

  const commitMessage = typeof obj.commitMessage === 'string' ? obj.commitMessage.trim() : ''
  const rawFiles = Array.isArray(obj.files) ? obj.files : []
  const files: FixPatchFile[] = []
  for (const entry of rawFiles) {
    const f = (entry && typeof entry === 'object' ? entry : {}) as Record<string, unknown>
    const path = typeof f.path === 'string' ? f.path.trim() : ''
    const contents = typeof f.contents === 'string' ? f.contents : ''
    if (!path || !contents) continue
    files.push({ path, contents })
  }
  if (!commitMessage || files.length === 0) return undefined

  const branchName =
    typeof obj.branchName === 'string' && obj.branchName.trim() ? obj.branchName.trim() : undefined
  return { commitMessage, branchName, files }
}

/** Whether an action is an applicable code fix (approved + carries a patch). */
export function isApplicableFix(action: EntityAction): boolean {
  return action.type === 'healing.fix' && readActionPatch(action) !== undefined
}

/** Derives a unique, valid branch name from the patch hint (or a default). */
function buildBranchName(patch: FixPatch): string {
  const hint = (patch.branchName ?? 'entity/fix')
    .replace(/^refs\/heads\//, '')
    .replace(/[^a-zA-Z0-9._/-]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^[-/]+|[-/]+$/g, '')
  const base = hint || 'entity/fix'
  return `${base}-${Date.now().toString(36)}`
}

function buildPrBody(action: EntityAction, patch: FixPatch): string {
  const diagnosis = typeof action.payload?.diagnosis === 'string' ? action.payload.diagnosis : ''
  const fileList = patch.files.map((f) => `- \`${f.path}\``).join('\n')
  return [
    'Opened by the SheetInvoicer **Entity** from an admin-approved fix proposal.',
    '',
    '> This PR was generated by an AI fix proposal and **approved by a human admin**.',
    '> It is **not** auto-merged or auto-deployed: CI must pass and a human must',
    '> review and merge it. Closing this PR (or rolling the action back) discards it.',
    '',
    `**Action:** ${action.id}`,
    '',
    '**Files changed:**',
    fileList,
    '',
    '**Diagnosis:**',
    '',
    diagnosis || '_No diagnosis recorded._',
  ].join('\n')
}

/**
 * Builds an {@link Executor} that applies an approved fix by opening a pull
 * request: it branches off the base ref, writes each patched file, and opens the
 * PR. On any failure mid-way it deletes the partial branch so no dangling state
 * is left behind, then rethrows so the SafetyController records the action as
 * `failed`. It never merges or deploys.
 */
export function createGitPrExecutor(git: GitClient): Executor {
  return async (action) => {
    const patch = readActionPatch(action)
    if (!patch) {
      throw new Error('This action has no applicable patch and cannot be applied.')
    }

    const base = await git.getBaseRef()
    const branch = buildBranchName(patch)
    await git.createBranch(branch, base.sha)

    try {
      for (const file of patch.files) {
        await git.putFile(branch, file.path, file.contents, patch.commitMessage)
      }
      const pr = await git.openPullRequest(branch, patch.commitMessage, buildPrBody(action, patch))
      const rollbackState: GitRollbackState = { prNumber: pr.number, branch }
      return {
        result: {
          prUrl: pr.url,
          prNumber: pr.number,
          branch,
          baseBranch: base.branch,
          files: patch.files.map((f) => f.path),
          appliedAt: new Date().toISOString(),
        },
        rollbackState: rollbackState as unknown as Record<string, unknown>,
      }
    } catch (err) {
      // Best-effort cleanup so a half-applied patch leaves no dangling branch.
      try {
        await git.deleteBranch(branch)
      } catch {
        /* ignore cleanup failures; surface the original error */
      }
      throw err
    }
  }
}

/** Resolved GitHub configuration. Missing token/repo disables Apply. */
export interface GitHubEnv {
  token?: string
  /** `owner/name`. */
  repo?: string
  baseBranch?: string
  fetchImpl?: typeof fetch
}

/** Reads GitHub configuration from `process.env`. */
export function readGitHubEnv(): GitHubEnv {
  return {
    token: process.env.GITHUB_TOKEN,
    repo: process.env.GITHUB_REPO,
    baseBranch: process.env.GITHUB_BASE_BRANCH,
  }
}

/** Whether GitHub is configured well enough to open PRs. */
export function isGitConfigured(env: GitHubEnv = readGitHubEnv()): boolean {
  return Boolean(env.token && env.repo)
}

function toBase64(value: string): string {
  if (typeof Buffer !== 'undefined') return Buffer.from(value, 'utf8').toString('base64')
  // Browser/edge fallback (not used on the nodejs runtime).
  return btoa(unescape(encodeURIComponent(value)))
}

/**
 * Production {@link GitClient} backed by the GitHub REST API. Throws a clear
 * error if `GITHUB_TOKEN`/`GITHUB_REPO` are unset so a misconfiguration surfaces
 * as a failed action rather than a silent no-op.
 */
export function createGitHubClient(env: GitHubEnv = readGitHubEnv()): GitClient {
  const { token, repo } = env
  if (!token || !repo) {
    throw new Error('GitHub is not configured: set GITHUB_TOKEN and GITHUB_REPO (owner/name).')
  }
  const baseBranch = env.baseBranch?.trim() || 'main'
  const doFetch = env.fetchImpl ?? globalThis.fetch
  const apiBase = `https://api.github.com/repos/${repo}`

  async function request(method: string, path: string, body?: unknown): Promise<Record<string, unknown>> {
    const res = await doFetch(`${apiBase}${path}`, {
      method,
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: 'application/vnd.github+json',
        'X-GitHub-Api-Version': '2022-11-28',
        ...(body !== undefined ? { 'Content-Type': 'application/json' } : {}),
      },
      body: body !== undefined ? JSON.stringify(body) : undefined,
    })
    const text = await res.text()
    const json = text ? (JSON.parse(text) as Record<string, unknown>) : {}
    if (!res.ok) {
      const message = typeof json.message === 'string' ? json.message : res.statusText
      throw new Error(`GitHub ${method} ${path} failed (${res.status}): ${message}`)
    }
    return json
  }

  return {
    async getBaseRef() {
      const ref = await request('GET', `/git/ref/heads/${encodeURIComponent(baseBranch)}`)
      const object = (ref.object ?? {}) as Record<string, unknown>
      return { branch: baseBranch, sha: String(object.sha ?? '') }
    },

    async createBranch(name, fromSha) {
      await request('POST', '/git/refs', { ref: `refs/heads/${name}`, sha: fromSha })
    },

    async putFile(branch, path, contents, message) {
      // The contents API needs the current blob sha to update an existing file.
      let sha: string | undefined
      try {
        const existing = await request(
          'GET',
          `/contents/${encodeURIComponent(path).replace(/%2F/g, '/')}?ref=${encodeURIComponent(branch)}`,
        )
        if (typeof existing.sha === 'string') sha = existing.sha
      } catch {
        // 404 → the file is new; create it without a sha.
      }
      await request('PUT', `/contents/${encodeURIComponent(path).replace(/%2F/g, '/')}`, {
        message,
        content: toBase64(contents),
        branch,
        ...(sha ? { sha } : {}),
      })
    },

    async openPullRequest(branch, title, body) {
      const pr = await request('POST', '/pulls', { title, head: branch, base: baseBranch, body })
      return { number: Number(pr.number), url: String(pr.html_url ?? '') }
    },

    async closePullRequest(prNumber) {
      await request('PATCH', `/pulls/${prNumber}`, { state: 'closed' })
    },

    async deleteBranch(name) {
      await request('DELETE', `/git/refs/heads/${name}`)
    },

    async getPrChecks(prNumber) {
      const pr = await request('GET', `/pulls/${prNumber}`)
      const head = (pr.head ?? {}) as Record<string, unknown>
      const sha = String(head.sha ?? '')
      if (!sha) return { state: 'pending' }
      const runs = await request('GET', `/commits/${sha}/check-runs`)
      const checkRuns = Array.isArray(runs.check_runs) ? (runs.check_runs as Record<string, unknown>[]) : []
      if (checkRuns.length === 0) return { state: 'pending' }
      let anyPending = false
      for (const run of checkRuns) {
        if (run.status !== 'completed') {
          anyPending = true
          continue
        }
        const conclusion = String(run.conclusion ?? '')
        if (['failure', 'cancelled', 'timed_out', 'action_required'].includes(conclusion)) {
          return { state: 'failure' }
        }
      }
      return { state: anyPending ? 'pending' : 'success' }
    },
  }
}
