'use client'

import { useState, useEffect } from 'react'

// Simple translation map
const dict = {
  en: {
    'Dashboard': 'Dashboard',
    'Invoices': 'Invoices',
    'Clients': 'Clients',
    'Expenses': 'Expenses',
    'Save': 'Save',
    'Cancel': 'Cancel',
    'Delete': 'Delete',
    'Edit': 'Edit',
    'View': 'View',
    'Add': 'Add',
    'Create': 'Create',
    'Back': 'Back',
    'Search': 'Search',
    'Export': 'Export',
    'Total Invoices': 'Total Invoices',
    'Total Clients': 'Total Clients',
    'Total Revenue': 'Total Revenue',
    'Pending Amount': 'Pending Amount',
    'Recent Invoices': 'Recent Invoices',
    'View All': 'View All',
    'New Invoice': 'New Invoice',
    'Add Client': 'Add Client',
    'Mark as Sent': 'Mark as Sent',
    'Mark as Paid': 'Mark as Paid',
    'Download PDF': 'Download PDF',
    'Send Email': 'Send Email',
    'Pay Now': 'Pay Now',
    'Invoice Number': 'Invoice Number',
    'Due Date': 'Due Date',
    'Status': 'Status',
    'Amount': 'Amount',
    'Date': 'Date',
    'Subtotal': 'Subtotal',
    'Tax': 'Tax',
    'Discount': 'Discount',
    'Total': 'Total',
    'Currency': 'Currency',
    'Notes': 'Notes',
    'Description': 'Description',
    'Category': 'Category',
    'Login': 'Login',
    'Sign Up': 'Sign Up',
    'Logout': 'Logout',
    'Dark Mode': 'Dark Mode',
    'Light Mode': 'Light Mode',
    'Language': 'Language',
    'Subscription': 'Subscription',
    'Settings': 'Settings',
    'Reports': 'Reports',
    'Estimates': 'Estimates',
    'Recurring': 'Recurring',
    'Free': 'Free',
    'Pro': 'Pro',
    'Business': 'Business',
    'Upgrade': 'Upgrade',
    'Subscribe Now': 'Subscribe Now',
    'Welcome Back': 'Welcome Back',
    'Create Account': 'Create Account',
    'Forgot Password': 'Forgot Password',
    'Reset Password': 'Reset Password',
    'Update Password': 'Update Password',
    'Remember Me': 'Remember Me',
    'Sign in with Google': 'Sign in with Google',
  },
  es: {
    'Dashboard': 'Tablero',
    'Invoices': 'Facturas',
    'Clients': 'Clientes',
    'Expenses': 'Gastos',
    'Save': 'Guardar',
    'Cancel': 'Cancelar',
    'Delete': 'Eliminar',
    'Edit': 'Editar',
    'View': 'Ver',
    'Add': 'Agregar',
    'Create': 'Crear',
    'Back': 'Atrás',
    'Search': 'Buscar',
    'Export': 'Exportar',
    'Total Invoices': 'Facturas totales',
    'Total Clients': 'Clientes totales',
    'Total Revenue': 'Ingresos totales',
    'Pending Amount': 'Monto pendiente',
    'Recent Invoices': 'Facturas recientes',
    'View All': 'Ver todo',
    'New Invoice': 'Nueva factura',
    'Add Client': 'Agregar cliente',
    'Mark as Sent': 'Marcar como enviada',
    'Mark as Paid': 'Marcar como pagada',
    'Download PDF': 'Descargar PDF',
    'Send Email': 'Enviar correo',
    'Pay Now': 'Pagar ahora',
    'Invoice Number': 'Número de factura',
    'Due Date': 'Fecha de vencimiento',
    'Status': 'Estado',
    'Amount': 'Monto',
    'Date': 'Fecha',
    'Subtotal': 'Subtotal',
    'Tax': 'Impuesto',
    'Discount': 'Descuento',
    'Total': 'Total',
    'Currency': 'Moneda',
    'Notes': 'Notas',
    'Description': 'Descripción',
    'Category': 'Categoría',
    'Login': 'Iniciar sesión',
    'Sign Up': 'Registrarse',
    'Logout': 'Cerrar sesión',
    'Dark Mode': 'Modo oscuro',
    'Light Mode': 'Modo claro',
    'Language': 'Idioma',
    'Subscription': 'Suscripción',
    'Settings': 'Configuración',
    'Reports': 'Informes',
    'Estimates': 'Presupuestos',
    'Recurring': 'Recurrentes',
    'Free': 'Gratis',
    'Pro': 'Pro',
    'Business': 'Empresarial',
    'Upgrade': 'Actualizar',
    'Subscribe Now': 'Suscribirse ahora',
    'Welcome Back': 'Bienvenido de nuevo',
    'Create Account': 'Crear cuenta',
    'Forgot Password': 'Olvidé mi contraseña',
    'Reset Password': 'Restablecer contraseña',
    'Update Password': 'Actualizar contraseña',
    'Remember Me': 'Recordarme',
    'Sign in with Google': 'Iniciar sesión con Google',
  },
  fr: {
    'Dashboard': 'Tableau de bord',
    'Invoices': 'Factures',
    'Clients': 'Clients',
    'Expenses': 'Dépenses',
    'Save': 'Enregistrer',
    'Cancel': 'Annuler',
    'Delete': 'Supprimer',
    'Edit': 'Modifier',
    'View': 'Voir',
    'Add': 'Ajouter',
    'Create': 'Créer',
    'Back': 'Retour',
    'Search': 'Rechercher',
    'Export': 'Exporter',
    'Total Invoices': 'Factures totales',
    'Total Clients': 'Clients totaux',
    'Total Revenue': 'Revenu total',
    'Pending Amount': 'Montant en attente',
    'Recent Invoices': 'Factures récentes',
    'View All': 'Voir tout',
    'New Invoice': 'Nouvelle facture',
    'Add Client': 'Ajouter un client',
    'Mark as Sent': 'Marquer comme envoyée',
    'Mark as Paid': 'Marquer comme payée',
    'Download PDF': 'Télécharger PDF',
    'Send Email': 'Envoyer un email',
    'Pay Now': 'Payer maintenant',
    'Invoice Number': 'Numéro de facture',
    'Due Date': "Date d'échéance",
    'Status': 'Statut',
    'Amount': 'Montant',
    'Date': 'Date',
    'Subtotal': 'Sous-total',
    'Tax': 'Taxe',
    'Discount': 'Réduction',
    'Total': 'Total',
    'Currency': 'Devise',
    'Notes': 'Notes',
    'Description': 'Description',
    'Category': 'Catégorie',
    'Login': 'Connexion',
    'Sign Up': "S'inscrire",
    'Logout': 'Déconnexion',
    'Dark Mode': 'Mode sombre',
    'Light Mode': 'Mode clair',
    'Language': 'Langue',
    'Subscription': 'Abonnement',
    'Settings': 'Paramètres',
    'Reports': 'Rapports',
    'Estimates': 'Devis',
    'Recurring': 'Récurrentes',
    'Free': 'Gratuit',
    'Pro': 'Pro',
    'Business': 'Entreprise',
    'Upgrade': "Mettre à niveau",
    'Subscribe Now': "S'abonner maintenant",
    'Welcome Back': 'Bon retour',
    'Create Account': 'Créer un compte',
    'Forgot Password': 'Mot de passe oublié',
    'Reset Password': 'Réinitialiser le mot de passe',
    'Update Password': 'Mettre à jour le mot de passe',
    'Remember Me': 'Se souvenir de moi',
    'Sign in with Google': 'Se connecter avec Google',
  },
  ar: {
    'Dashboard': 'لوحة التحكم',
    'Invoices': 'الفواتير',
    'Clients': 'العملاء',
    'Expenses': 'المصروفات',
    'Save': 'حفظ',
    'Cancel': 'إلغاء',
    'Delete': 'حذف',
    'Edit': 'تعديل',
    'View': 'عرض',
    'Add': 'إضافة',
    'Create': 'إنشاء',
    'Back': 'رجوع',
    'Search': 'بحث',
    'Export': 'تصدير',
    'Total Invoices': 'إجمالي الفواتير',
    'Total Clients': 'إجمالي العملاء',
    'Total Revenue': 'إجمالي الإيرادات',
    'Pending Amount': 'المبلغ المعلق',
    'Recent Invoices': 'الفواتير الأخيرة',
    'View All': 'عرض الكل',
    'New Invoice': 'فاتورة جديدة',
   
'Add Client': 'إضافة عميل',
    'Mark as Sent': 'تحديد كمرسلة',
    'Mark as Paid': 'تحديد كمدفوعة',
    'Download PDF': 'تحميل PDF',
    'Send Email': 'إرسال بريد',
    'Pay Now': 'ادفع الآن',
    'Invoice Number': 'رقم الفاتورة',
    'Due Date': 'تاريخ الاستحقاق',
    'Status': 'الحالة',
    'Amount': 'المبلغ',
    'Date': 'التاريخ',
    'Subtotal': 'المجموع الفرعي',
    'Tax': 'الضريبة',
    'Discount': 'الخصم',
    'Total': 'المجموع',
    'Currency': 'العملة',
    'Notes': 'ملاحظات',
    'Description': 'الوصف',
    'Category': 'الفئة',
    'Login': 'تسجيل الدخول',
    'Sign Up': 'التسجيل',
    'Logout': 'تسجيل الخروج',
    'Dark Mode': 'الوضع الداكن',
    'Light Mode': 'الوضع المضيء',
    'Language': 'اللغة',
    'Subscription': 'الاشتراك',
    'Settings': 'الإعدادات',
    'Reports': 'التقارير',
    'Estimates': 'تقديرات',
    'Recurring': 'متكرر',
    'Free': 'مجاني',
    'Pro': 'احترافي',
    'Business': 'تجاري',
    'Upgrade': 'ترقية',
    'Subscribe Now': 'اشترك الآن',
    'Welcome Back': 'مرحباً بعودتك',
    'Create Account': 'إنشاء حساب',
    'Forgot Password': 'نسيت كلمة المرور',
    'Reset Password': 'إعادة تعيين كلمة المرور',
    'Update Password': 'تحديث كلمة المرور',
    'Remember Me': 'تذكرني',
    'Sign in with Google': 'تسجيل الدخول عبر Google',
  },
}

export function useTranslate() {
  const [locale, setLocale] = useState('en')
  
  useEffect(() => {
    const saved = localStorage.getItem('app-language')
    if (saved && dict[saved]) {
      setLocale(saved)
    }
  }, [])
  
  const t = (text) => {
    return dict[locale]?.[text] || dict.en[text] || text
  }
  
  return { t, locale }
}
